name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

 - name: Posting Coverage
      env:
        super_secret: ${{ secrets.CODECOV_TOKEN }}
      run: |
        pipenv run codecov